import type { BookListing } from './types';

export const bookSwapData: BookListing[] = [
  {
    id: 1,
    title: 'Data Structures and Algorithms in C++',
    author: 'Michael T. Goodrich, Roberto Tamassia, David M. Mount',
    price: 45.0,
    sellerName: 'Alice Johnson',
    sellerContact: 'alice.j@example.com',
    imageUrl: 'https://placehold.co/300x400.png',
    imageAiHint: 'book cover',
    course: 'CS101',
  },
  {
    id: 2,
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    price: 25.0,
    sellerName: 'Bob Williams',
    sellerContact: 'bob.w@example.com',
    imageUrl: 'https://placehold.co/300x400.png',
    imageAiHint: 'book cover',
    course: 'CS205',
  },
  {
    id: 3,
    title: 'Introduction to the Theory of Computation',
    author: 'Michael Sipser',
    price: 50.0,
    sellerName: 'Charlie Brown',
    sellerContact: '555-123-4567',
    imageUrl: 'https://placehold.co/300x400.png',
    imageAiHint: 'book cover',
    course: 'CS301',
  },
  {
    id: 4,
    title: 'The Pragmatic Programmer: Your Journey to Mastery',
    author: 'David Thomas, Andrew Hunt',
    price: 'Free',
    sellerName: 'Diana Miller',
    sellerContact: 'diana.m@example.com',
    imageUrl: 'https://placehold.co/300x400.png',
    imageAiHint: 'book cover',
    course: 'General',
  },
  {
    id: 5,
    title: 'Cracking the Coding Interview',
    author: 'Gayle Laakmann McDowell',
    price: 30.0,
    sellerName: 'Ethan Garcia',
    sellerContact: '555-987-6543',
    imageUrl: 'https://placehold.co/300x400.png',
    imageAiHint: 'book cover',
    course: 'Career Prep',
  },
  {
    id: 6,
    title: 'Automate the Boring Stuff with Python',
    author: 'Al Sweigart',
    price: 15.0,
    sellerName: 'Fiona Davis',
    sellerContact: 'fiona.d@example.com',
    imageUrl: 'https://placehold.co/300x400.png',
    imageAiHint: 'book cover',
    course: 'CS110',
  },
];
